### ISSUE TITLE
Reason for detaching 'on' listener

### ISSUE THREAD

**Issue by mwhitaker** [laurenzlong/say-that#2]
Thank you for a great demo at I/O 17 and for sharing your code. This is not really an issue, but I was wondering if you could explain why you need to [detach]((https://github.com/laurenzlong/say-that/blob/master/public/scripts/index.js#L148)) the 'on' listener from the database reference (and then add it back) in a few of your functions?

Kind regards,
Michael

**Comment by laurenzlong** [comment]
Thanks for the question @mwhitaker , and sorry for the very late response! It is to prevent duplication of UI elements. Otherwise, we get into a condition where there are two of the same listeners on a database node, and 2 pills are added for each database write.
